### ISSUE TITLE
ia-csharp

### ISSUE THREAD

**Issue by mnivet** [game-of-code/ia-java#3]
J'ai mis au propre le portage C# que j'ai fait lors du codelab au devfest de Nantes vendredi matin

Vous pouvez le trouver ici:
https://github.com/mnivet/ia-csharp

j'ai tenté de transférer l'ownership à game-of-code mais sans succès...

**Comment by mbrechet** [comment]
Salut, super, merci pour le travail réalisé, j'ai tenté de fork le repo ce matin mais je pense que github a des petits soucis techniques...

**Comment by mbrechet** [comment]
C'est bon je viens de fork le repo. Merci pour la contribution
